In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Credit_risk_cleaned.csv')
df.head()

,CLIENT_ID,PERSON_AGE,PERSON_INCOME,PERSON_HOME_OWNERSHIP,PERSON_EMP_LENGTH,LOAN_INTENT,LOAN_GRADE,LOAN_AMNT,LOAN_INT_RATE,LOAN_STATUS,...,CITY_LONGITUDE,EMPLOYMENT_TYPE,LOAN_TERM_MONTHS,LOAN_TO_INCOME_RATIO,OTHER_DEBT,DEBT_TO_INCOME_RATIO,OPEN_ACCOUNTS,CREDIT_UTILIZATION_RATIO,PAST_DELINQUENCIES,LOAN_STATUS_DESC
0,CUST_00001,22,59000,RENT,4,PERSONAL,D,35000,16.02,1,...,-79.3832,Self-employed,36,0.593220,8402.453850,0.735635,14,0.495557,0,Default
1,CUST_00002,21,9600,OWN,5,EDUCATION,B,1000,11.14,0,...,-79.3832,Full-time,36,0.104167,1607.802794,0.271646,10,0.585436,3,Non-Default
2,CUST_00003,25,9600,MORTGAGE,1,MEDICAL,C,5500,12.87,1,...,-3.9436,Full-time,36,0.572917,2760.505633,0.860469,14,0.750732,0,Default
3,CUST_00004,23,65500,RENT,4,MEDICAL,C,35000,15.23,1,...,-123.1207,Part-time,12,0.534351,7155.286150,0.643592,15,0.379333,0,Default
4,CUST_00005,24,54400,RENT,8,MEDICAL,C,35000,14.27,1,...,-78.8784,Part-time,36,0.643382,15626.153439,0.930628,4,0.228103,0,Default

In [3]:
df.describe()

,PERSON_AGE,PERSON_INCOME,PERSON_EMP_LENGTH,LOAN_AMNT,LOAN_INT_RATE,LOAN_STATUS,LOAN_PERCENT_INCOME,CB_PERSON_CRED_HIST_LENGTH,CITY_LATITUDE,CITY_LONGITUDE,LOAN_TERM_MONTHS,LOAN_TO_INCOME_RATIO,OTHER_DEBT,DEBT_TO_INCOME_RATIO,OPEN_ACCOUNTS,CREDIT_UTILIZATION_RATIO,PAST_DELINQUENCIES
count,32576.000000,3.257600e+04,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000,32576.000000
mean,27.718044,6.588214e+04,4.760529,9589.117755,11.009683,0.218197,0.170212,5.803966,45.408103,-63.800079,38.501965,0.170562,11529.404627,0.345209,8.042240,0.499899,0.505188
std,6.204990,5.253499e+04,3.981064,6321.886846,3.219534,0.413029,0.106778,4.053791,7.644799,46.616393,16.012811,0.107045,11315.622605,0.129391,4.328094,0.259520,0.711772
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000,29.760400,-123.365600,12.000000,0.000789,225.207376,0.064502,0.000000,0.050001,0.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.880000,0.000000,0.090000,3.000000,40.712800,-96.797000,24.000000,0.089711,5386.246343,0.251262,4.000000,0.275369,0.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.995555,0.000000,0.150000,4.000000,46.813900,-75.697200,36.000000,0.148148,8994.217919,0.333190,8.000000,0.500291,0.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.463542,0.000000,0.230000,8.000000,51.507400,-3.943600,60.000000,0.229167,14559.804486,0.423142,12.000000,0.725057,1.000000
max,94.000000,2.039784e+06,41.000000,35000.000000,23.220000,1.000000,0.830000,30.000000,55.953300,-0.127800,60.000000,0.830000,399125.752964,1.000000,15.000000,0.949998,6.000000

In [4]:
df.shape

(32576, 30)

In [5]:
df.isnull().sum()

CLIENT_ID                     0
PERSON_AGE                    0
PERSON_INCOME                 0
PERSON_HOME_OWNERSHIP         0
PERSON_EMP_LENGTH             0
LOAN_INTENT                   0
LOAN_GRADE                    0
LOAN_AMNT                     0
LOAN_INT_RATE                 0
LOAN_STATUS                   0
LOAN_PERCENT_INCOME           0
CB_PERSON_DEFAULT_ON_FILE     0
CB_PERSON_CRED_HIST_LENGTH    0
GENDER                        0
MARITAL_STATUS                0
EDUCATION_LEVEL               0
COUNTRY                       0
STATE                         0
CITY                          0
CITY_LATITUDE                 0
CITY_LONGITUDE                0
EMPLOYMENT_TYPE               0
LOAN_TERM_MONTHS              0
LOAN_TO_INCOME_RATIO          0
OTHER_DEBT                    0
DEBT_TO_INCOME_RATIO          0
OPEN_ACCOUNTS                 0
CREDIT_UTILIZATION_RATIO      0
PAST_DELINQUENCIES            0
LOAN_STATUS_DESC              0
dtype: int64

In [6]:
df.duplicated().sum()

0

In [7]:
df.dtypes

CLIENT_ID                      object
PERSON_AGE                      int64
PERSON_INCOME                   int64
PERSON_HOME_OWNERSHIP          object
PERSON_EMP_LENGTH               int64
LOAN_INTENT                    object
LOAN_GRADE                     object
LOAN_AMNT                       int64
LOAN_INT_RATE                 float64
LOAN_STATUS                     int64
LOAN_PERCENT_INCOME           float64
CB_PERSON_DEFAULT_ON_FILE      object
CB_PERSON_CRED_HIST_LENGTH      int64
GENDER                         object
MARITAL_STATUS                 object
EDUCATION_LEVEL                object
COUNTRY                        object
STATE                          object
CITY                           object
CITY_LATITUDE                 float64
CITY_LONGITUDE                float64
EMPLOYMENT_TYPE                object
LOAN_TERM_MONTHS                int64
LOAN_TO_INCOME_RATIO          float64
OTHER_DEBT                    float64
DEBT_TO_INCOME_RATIO          float64
OPEN_ACCOUNTS                   int64
CREDIT_UTILIZATION_RATIO      float64
PAST_DELINQUENCIES              int64
LOAN_STATUS_DESC               object
dtype: object

In [8]:
# Ensure consistency in categorical columns
# List of columns that need cleaning (strip + lowercase)
columns_to_clean = ['CLIENT_ID', 'PERSON_HOME_OWNERSHIP', 'LOAN_INTENT','LOAN_GRADE','CB_PERSON_DEFAULT_ON_FILE','GENDER','MARITAL_STATUS',
                    'EDUCATION_LEVEL','COUNTRY','STATE','CITY','EMPLOYMENT_TYPE','LOAN_STATUS_DESC']

# For loop version
for col in columns_to_clean:
    df[col] = df[col].str.strip().str.lower()

In [9]:
df.drop(columns = ['CITY_LATITUDE','CITY_LONGITUDE','CLIENT_ID','LOAN_STATUS_DESC'],inplace = True)

In [10]:
df.columns

Index(['PERSON_AGE', 'PERSON_INCOME', 'PERSON_HOME_OWNERSHIP',
       'PERSON_EMP_LENGTH', 'LOAN_INTENT', 'LOAN_GRADE', 'LOAN_AMNT',
       'LOAN_INT_RATE', 'LOAN_STATUS', 'LOAN_PERCENT_INCOME',
       'CB_PERSON_DEFAULT_ON_FILE', 'CB_PERSON_CRED_HIST_LENGTH', 'GENDER',
       'MARITAL_STATUS', 'EDUCATION_LEVEL', 'COUNTRY', 'STATE', 'CITY',
       'EMPLOYMENT_TYPE', 'LOAN_TERM_MONTHS', 'LOAN_TO_INCOME_RATIO',
       'OTHER_DEBT', 'DEBT_TO_INCOME_RATIO', 'OPEN_ACCOUNTS',
       'CREDIT_UTILIZATION_RATIO', 'PAST_DELINQUENCIES'],
      dtype='object')

In [11]:
df.head()

,PERSON_AGE,PERSON_INCOME,PERSON_HOME_OWNERSHIP,PERSON_EMP_LENGTH,LOAN_INTENT,LOAN_GRADE,LOAN_AMNT,LOAN_INT_RATE,LOAN_STATUS,LOAN_PERCENT_INCOME,...,STATE,CITY,EMPLOYMENT_TYPE,LOAN_TERM_MONTHS,LOAN_TO_INCOME_RATIO,OTHER_DEBT,DEBT_TO_INCOME_RATIO,OPEN_ACCOUNTS,CREDIT_UTILIZATION_RATIO,PAST_DELINQUENCIES
0,22,59000,rent,4,personal,d,35000,16.02,1,0.59,...,ontario,toronto,self-employed,36,0.593220,8402.453850,0.735635,14,0.495557,0
1,21,9600,own,5,education,b,1000,11.14,0,0.10,...,ontario,toronto,full-time,36,0.104167,1607.802794,0.271646,10,0.585436,3
2,25,9600,mortgage,1,medical,c,5500,12.87,1,0.57,...,wales,swansea,full-time,36,0.572917,2760.505633,0.860469,14,0.750732,0
3,23,65500,rent,4,medical,c,35000,15.23,1,0.53,...,bc,vancouver,part-time,12,0.534351,7155.286150,0.643592,15,0.379333,0
4,24,54400,rent,8,medical,c,35000,14.27,1,0.55,...,new york,buffalo,part-time,36,0.643382,15626.153439,0.930628,4,0.228103,0

In [12]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [13]:
numeric_cols = [
    'PERSON_AGE', 'PERSON_INCOME', 'PERSON_EMP_LENGTH',
    'LOAN_AMNT', 'LOAN_INT_RATE', 'LOAN_PERCENT_INCOME',
    'CB_PERSON_CRED_HIST_LENGTH', 'LOAN_TERM_MONTHS',
    'LOAN_TO_INCOME_RATIO', 'OTHER_DEBT', 'DEBT_TO_INCOME_RATIO',
    'OPEN_ACCOUNTS', 'CREDIT_UTILIZATION_RATIO', 'PAST_DELINQUENCIES'
]

In [14]:
scaler = StandardScaler()

In [15]:
categorical_cols = [
    'PERSON_HOME_OWNERSHIP', 'LOAN_INTENT', 'LOAN_GRADE',
    'CB_PERSON_DEFAULT_ON_FILE', 'GENDER', 'MARITAL_STATUS',
    'EDUCATION_LEVEL', 'EMPLOYMENT_TYPE','COUNTRY', 'STATE', 'CITY'
]

In [16]:
encoder = OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False)

In [17]:
X = df.drop(columns='LOAN_STATUS')

In [18]:
y = df[['LOAN_STATUS']]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [21]:
print(f"Training samples: {len(X_train):,}")
print(f"Test samples:     {len(X_test):,}\n")

Training samples: 26,060
Test samples:     6,516

In [22]:
X_train_num_scaled = scaler.fit_transform(X_train[numeric_cols])
X_test_num_scaled  = scaler.transform(X_test[numeric_cols])

In [23]:
X_train_cat_encoded = encoder.fit_transform(X_train[categorical_cols])
X_test_cat_encoded  = encoder.transform(X_test[categorical_cols])

In [24]:
X_train_final = np.hstack([X_train_num_scaled, X_train_cat_encoded])
X_test_final  = np.hstack([X_test_num_scaled,  X_test_cat_encoded])

# LOGISTIC REGRESSION

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
log = LogisticRegression()

In [28]:
log.fit(X_train_final,y_train)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [29]:
y_pred = log.predict(X_test_final)

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [31]:
acc = accuracy_score(y_test,y_pred)
acc

0.8690914671577655

In [32]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[4842,  252],
       [ 601,  821]], dtype=int64)

# LINEAR REGRESSION

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
model = LinearRegression()

In [36]:
model.fit(X_train_final,y_train)

LinearRegression()

In [37]:
y_pred_linear = model.predict(X_test_final)

In [38]:
# Convert regression output → binary class 
y_pred_class = (y_pred_linear > 0.5).astype(int)   # the threshold at 0.5

In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
from sklearn.metrics import root_mean_squared_error

In [41]:
mae = mean_absolute_error(y_test,y_pred_linear)
mae

0.2429200811134371

In [42]:
mse = mean_squared_error(y_test,y_pred_linear)
mse

0.10902679242717389

In [43]:
R2 = r2_score(y_test,y_pred_linear)
R2

0.360947041784382

In [44]:
RMSE = root_mean_squared_error(y_test,y_pred_linear)
RMSE

0.3301920538522602

In [45]:
acc_linear = accuracy_score(y_test, y_pred_class)
acc_linear

0.864487415592388

In [46]:
cm_linear = confusion_matrix(y_test, y_pred_class)
cm_linear

array([[4863,  231],
       [ 652,  770]], dtype=int64)

# Decision Tree Classifier

In [48]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [49]:
dt_model = DecisionTreeClassifier(max_depth=5 , random_state=42)

In [50]:
dt_model.fit(X_train_final,y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [51]:
y_pred_dt = dt_model.predict(X_test_final)

In [52]:
acc_dt = accuracy_score(y_test,y_pred_dt)
acc_dt

0.903621853898097

# Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier

In [55]:
rf_model = RandomForestClassifier(n_estimators=100, random_state = 42)

In [56]:
rf_model.fit(X_train_final,y_train)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(random_state=42)

In [57]:
y_pred_rf = rf_model.predict(X_test_final)

In [58]:
acc_rf = accuracy_score(y_test,y_pred_rf)
acc_rf

0.9246470227133211